use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "grammar.pest"]
pub struct FusionParser;

// Explicitly re-export the Rule enum generated by pest_derive
pub use self::Rule::*;

// This enum is automatically generated by pest_derive from your grammar
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Rule {
    // Main structure
    program,
    statement,
    block,

    // Expressions
    expression,
    addition,
    subtraction,
    integer,
    func_call,
    param_list,
    string_lit,
    inner_string,
    ident,

    // Function definitions
    func_definition,
    param_def_list,
    param_def,

    // Imports
    c_import,

    // Whitespace and utility rules
    WHITESPACE,
    NEWLINE,
    WS,
    whitespace,
    alpha,
    digit,

    // End of input marker
    EOI,
}
