WHITESPACE = _{ " " | "\t" | "\n" | "\r" }

program = { SOI ~ statement* ~ EOI }
statement = { expression | block | func_definition } // Replace addition with expression
expression = { addition | integer } // Expressions can be additions or integers
addition = { integer ~ "+" ~ integer }
func_definition = { "fn" ~ ident ~ "()" ~ block }
block = { "{" ~ statement* ~ "}" }
integer = { "-"? ~ ASCII_DIGIT+ }
ident = @{ (alpha | digit)+ }
alpha = _{ 'a'..'z' | 'A'..'Z' }
digit = _{ '0'..'9' }
